### ISSUE TITLE
Can write CSV with UTF-8

### ISSUE THREAD

**Issue by bonlv2000** [ThomasPe/Azure.Data.Tables-Extensions#6]
![image](https://github.com/ThomasPe/Azure.Data.Tables-Extensions/assets/59633180/ecab954c-e6d8-42f8-af8a-336aa3800ff2)

```
using StreamWriter writer = File.CreateText("output.csv");
await tableClient.ExportCSVAsync(writer);
```

It not working with UTF-8!
Help.

**Comment by ThomasPe** [comment]
Hey, I just checked. When opening the CSV in VS Code everything looks fine. You probably opened the CSV directly in Excel, right? There I also see issues, unless I import the CSV, then it seems fine again.

Could you double-check if that's the case for you as well?
Using the tool with `using StreamWriter writer = File.CreateText("test.csv");` does explicitly write in UTF-8.

So hopefully just an Excel issue :)
